version: "3.2"

services:

  apache:
    build:
      context: ./
      dockerfile: dockerfile-apache
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysql

  mysql:
      image: mysql
      container_name: mysql
      restart: always
      environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress
      ports:
        - "3636:3306"
      volumes:
        - "./data/db/mysql:/var/lib/mysql"